services:
  - type: web
    name: bot-dr-pantich
    env: node
    plan: free
    rootDir: bot
    buildCommand: npm install
    startCommand: node rolo-bot.js
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: WORKER_URL
        value: https://sparkling-lake-e9b6.repantich.workers.dev
      - key: DATA_DIR
        value: /tmp
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_IDS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
